language: python
python:
  - "2.6"
  - "2.7"
  - "pypy"
env:
  global: 
    - PYCURL_SSL_LIBRARY=openssl
  matrix:
    - LXML_VERSION="<3"
    - LXML_VERSION=""
# Need to install pycurl separately as urlgrabber needs it at setup
install:
  - pip install pycurl
  - pip install lxml$LXML_VERSION
  - pip install -r requirements.txt
  - pip install -r .travis-requirements.txt
script:
  - coverage run --source=. ./setup.py test
after_script:
  - coveralls
matrix:
  exclude:
    - python: "pypy"
      env: LXML_VERSION="<3"
